<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Cyberpilot</RootNamespace>
    <AssemblyName>Cyberpilot.Sdk.Exe</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\copilot-sdk\Cyberpilot.Sdk.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Cyberpilot.Sdk.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
