// <auto-generated />
using System;
using Cyberpilot.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cyberpilot.Persistence.Migrations
{
    [DbContext(typeof(CyberpilotDbContext))]
    [Migration("20260511232804_AddRemotePipelineFields")]
    partial class AddRemotePipelineFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowMissingDocs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BranchName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStage")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("GitHubActionsRunId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SkipDeliver")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StageTimeoutMinutes")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetRepository")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorktreePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueNumber");

                    b.HasIndex("Status");

                    b.ToTable("PipelineRuns");
                });

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineStageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("StageName");

                    b.ToTable("PipelineStageLogs");
                });

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineStageLog", b =>
                {
                    b.HasOne("Cyberpilot.Persistence.PipelineRun", "Run")
                        .WithMany("StageLogs")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineRun", b =>
                {
                    b.Navigation("StageLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
