// <auto-generated />
using System;
using Cyberpilot.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cyberpilot.Persistence.Migrations
{
    [DbContext(typeof(CyberpilotDbContext))]
    [Migration("20260518193410_AddToolArgsToToolFailure")]
    partial class AddToolArgsToToolFailure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineApproval", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecidedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedRole")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeStageName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Timing")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("StageName");

                    b.HasIndex("Status");

                    b.ToTable("PipelineApprovals");
                });

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineArtifact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractVersion")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StageLogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uri")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RunId");

                    b.HasIndex("StageLogId");

                    b.HasIndex("StageName");

                    b.ToTable("PipelineArtifacts");
                });

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineDispatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("PipelineDispatches");
                });

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineEvidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StageLogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uri")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("RunId");

                    b.HasIndex("StageLogId");

                    b.HasIndex("StageName");

                    b.ToTable("PipelineEvidence");
                });

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineRun", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowMissingDocs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BenchmarkResetAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BranchName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractVersion")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStage")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("CyberpilotSha")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("GitHubActionsRunId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("IssueUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PipelineDefinitionName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PipelineDefinitionVersion")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyProfileName")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Repository")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SkipDeliver")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StageTimeoutMinutes")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetRepoSha")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetRepository")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggeredBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorktreePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IssueNumber");

                    b.HasIndex("Status");

                    b.ToTable("PipelineRuns");
                });

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineStageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiCallIds")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CacheReadTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CacheWriteTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfiguredModel")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationMs")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("EstimatedCostUsd")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FailedToolCallCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FallbackModel")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FallbackReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("PremiumRequestCost")
                        .HasColumnType("REAL");

                    b.Property<string>("ProviderCallIds")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ReachedIdle")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReasoningTokens")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RetryReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedModel")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("StageResultContractVersion")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("StageResultJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ToolCallCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TurnCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("WasAborted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("StageName");

                    b.ToTable("PipelineStageLogs");
                });

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineToolFailure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StageLogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolArgs")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolCallId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("StageLogId");

                    b.HasIndex("StageName");

                    b.HasIndex("ToolName");

                    b.ToTable("PipelineToolFailures");
                });

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineApproval", b =>
                {
                    b.HasOne("Cyberpilot.Persistence.PipelineRun", "Run")
                        .WithMany("Approvals")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineArtifact", b =>
                {
                    b.HasOne("Cyberpilot.Persistence.PipelineRun", "Run")
                        .WithMany("Artifacts")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cyberpilot.Persistence.PipelineStageLog", "StageLog")
                        .WithMany("Artifacts")
                        .HasForeignKey("StageLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Run");

                    b.Navigation("StageLog");
                });

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineDispatch", b =>
                {
                    b.HasOne("Cyberpilot.Persistence.PipelineRun", null)
                        .WithMany("Dispatches")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineEvidence", b =>
                {
                    b.HasOne("Cyberpilot.Persistence.PipelineRun", "Run")
                        .WithMany("Evidence")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cyberpilot.Persistence.PipelineStageLog", "StageLog")
                        .WithMany("Evidence")
                        .HasForeignKey("StageLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Run");

                    b.Navigation("StageLog");
                });

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineStageLog", b =>
                {
                    b.HasOne("Cyberpilot.Persistence.PipelineRun", "Run")
                        .WithMany("StageLogs")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineToolFailure", b =>
                {
                    b.HasOne("Cyberpilot.Persistence.PipelineRun", "Run")
                        .WithMany("ToolFailures")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cyberpilot.Persistence.PipelineStageLog", "StageLog")
                        .WithMany("ToolFailures")
                        .HasForeignKey("StageLogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Run");

                    b.Navigation("StageLog");
                });

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineRun", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Artifacts");

                    b.Navigation("Dispatches");

                    b.Navigation("Evidence");

                    b.Navigation("StageLogs");

                    b.Navigation("ToolFailures");
                });

            modelBuilder.Entity("Cyberpilot.Persistence.PipelineStageLog", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("Evidence");

                    b.Navigation("ToolFailures");
                });
#pragma warning restore 612, 618
        }
    }
}
